### ISSUE TITLE
Update RSSI trigger function

### ISSUE THREAD

**Issue by scottgchin** [scottgchin/delta5_race_timer#1]
Currently if the average RSSI is above the threshold limit (or lap trigger) this counts as a good lap read.  Look into using a rising edge detection or a peak detection to determine the trigger.  The trigger calibration could still set the minimum threshold required.

For reference:
https://www.tigoe.com/pcomp/code/arduinowiring/46/

**Comment by howflyquad** [comment]
I think this is complete in the current version of the code using the rssiTriggerBandwidth value.
