### ISSUE TITLE
not working on rpi 4b and newest piOS

### ISSUE THREAD

**Issue by pan-sattan** [scottgchin/delta5_race_timer#102]
hello,
I am struggling on my raspberry pi 4B 8gb version with newest PiOS with desktop... unable to run server
there are multiple errors like flask is missing etc

Any idea how to solve it?

**Comment by martinglass** [comment]
I'm not sure what support is available here anymore. If you don't get an answer (or even if you do), it maybe worth looking at Rotorhazard, which is a more up to date fork of Delta5, using the same hardware. 
https://github.com/RotorHazard/RotorHazard

**Comment by pan-sattan** [comment]
@martinglass thank you... rotorhazard version is realy working!
