### ISSUE TITLE
Clear Database separate by pilots list ,heats or Rounds. Store last database

### ISSUE THREAD

**Issue by maddust** [scottgchin/delta5_race_timer#25]
the ability to separate how the database is clear was a good feature . specially if you have a 30+ pilots events

if something need to be reset you dont have to start from 0 .

also in the latest version database is not been stored. when you turn off the system database resets.

**Comment by howflyquad** [comment]
The different database resets will come back at some point, we just need to figure out the best way to handle it. Don't want the heats or pilots reset while the saved races list is still looking for them. The options until multi event handling might be as simple as:
* Reset All
* Reset All but keep Pilots

I think this might be good enough for now.

**Comment by howflyquad** [comment]
Please see #26 for the database loss issue.

**Comment by howflyquad** [comment]
Pull request #32 adds the option to reset the database but keep the pilots list.
