### ISSUE TITLE
Delta5 integration in MultiGP LapSync Race Timing Desktop Software

### ISSUE THREAD

**Issue by kestux75** [scottgchin/delta5_race_timer#47]
It would be nice to have Delta5 in MultiGP LapSync Race Timing Desktop Software. 
https://www.facebook.com/groups/FPVRaceTimer/

**Comment by KHackbarth** [comment]
Delta5 is an option in LiveTime now. Lapsync is going away. The developer of Lapsync moved to LiveTime at the end of August. 

![delta5livetimemultigpohackit](https://user-images.githubusercontent.com/15882513/30237720-8268846a-94fd-11e7-9431-72693b3a1e21.JPG)

**Comment by scottgchin** [comment]
Correct. Our developers worked with LiveTime to integrate the D5RT.  It works great!
