### ISSUE TITLE
How does it integrate with live time?

### ISSUE THREAD

**Issue by spuder** [scottgchin/delta5_race_timer#60]
I'm just learning what live time is. The documentation says

>Alternatively, to use your Delta5 Race Timer hardware with 3rd party timing software, replace each reference of 'delta5server' with 'timingserver' in the following instructions.

Does live time run on the raspberry pi? 

There have been some facebook discussions around switching between the delta 5 server and live time. I'm trying to figure out if there is a way to run both services simultaneously and use a proxy to route network traffic based on the source url. 

Could you elaborate on why there is a need for 2 different services to be running?

**Comment by punkkills** [comment]
Livetime runs on a PC and communicates with the pi through the TimingServer.  The TimingServer does not have any more advanced features such as managing pilots and heats.  The delta5server is a race management tool.  It runs as a web app and provides a subset of the functionality of something like Livetime.  They have different requirements and goals so they are different apps.  They do run shared code for communicating with the arduinos.
