### ISSUE TITLE
Restore previous 'delta5node.ino'

### ISSUE THREAD

**Issue by ethomas997** [scottgchin/delta5_race_timer#89]
Commit d17dcdf43f90741d451240af1effb84ca40a5932 ("timing server LED") reverts the changes to 'delta5node.ino' that came in via the previous commit d0df60163cc21c1b55e4afff656acef83826c2ed ("Modified node to use freqMhzToRegVal() fn instead of table") for no apparent reason.  I think the [previous 'delta5node.ino'](https://github.com/scottgchin/delta5_race_timer/blob/d0df60163cc21c1b55e4afff656acef83826c2ed/src/delta5node/delta5node.ino) should be restored.

--ET

**Comment by scottgchin** [comment]
It was updated because on the LiveTime version, the user can manually input the frequency.  If the user submitted a frequency that wasn't in the table the system would lock up.  Is there an issue with using the current freqMhzToRegVal() calculation?

**Comment by scottgchin** [comment]
It should be restored now.

**Comment by ethomas997** [comment]
Yes, looks good now; thx.
